language: minimal

before_install:
  - curl -s https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.3/kustomize_2.0.3_linux_amd64
  - mv kustomize_2.0.3_linux_amd64 kustomize
  - chmod u+x kustomize

script: kustomize version

# jobs:
#   include:
#     - script: echo "Running unit tests (1)"
#     - script: echo "Running unit tests (2)"
#     - stage: GitHub Release
#       script: echo "Deploying to GitHub releases ..."
#       deploy:
#         provider: releases
#         api_key: $GITHUB_OAUTH_TOKEN
#         skip_cleanup: true
#         on:
#           tags: true