language: minimal

before_install:
  - curl -s -L https://github.com/kubernetes-sigs/kustomize/releases/latest | egrep -o '/kubernetes-sigs/kustomize/releases/download/v[0-9\.]*/kustomize.*_linux_amd64' | wget --base=http://github.com/ -i - -O kustomize
  - chmod u+x kustomize

script: kustomize version

# jobs:
#   include:
#     - script: echo "Running unit tests (1)"
#     - script: echo "Running unit tests (2)"
#     - stage: GitHub Release
#       script: echo "Deploying to GitHub releases ..."
#       deploy:
#         provider: releases
#         api_key: $GITHUB_OAUTH_TOKEN
#         skip_cleanup: true
#         on:
#           tags: true

