language: minimal

before_install:
  - opsys=linux
  - curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
    grep browser_download |\
    grep $opsys |\
    cut -d '"' -f 4 |\
    xargs curl -O -L
  - mv kustomize_*_${opsys}_amd64 kustomize
  - chmod u+x kustomize

script: kustomize version

# jobs:
#   include:
#     - script: echo "Running unit tests (1)"
#     - script: echo "Running unit tests (2)"
#     - stage: GitHub Release
#       script: echo "Deploying to GitHub releases ..."
#       deploy:
#         provider: releases
#         api_key: $GITHUB_OAUTH_TOKEN
#         skip_cleanup: true
#         on:
#           tags: true