apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
  - name: linuxserver/jackett
    newName: lsioarmhf/jackett
    newTag: latest
  - name: linuxserver/sonarr
    newName: lsioarmhf/sonarr
    newTag: latest
  - name: linuxserver/radarr
    newName: lsioarmhf/radarr
    newTag: latest
  - name: linuxserver/transmission
    newName: lsioarmhf/transmission
    newTag: latest
