apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

commonLabels:
  app: htpc

resources:
- jackett.yaml
- radarr.yaml
- sonarr.yaml
- transmission.yaml
- ingress.yaml

# patchesStrategicMerge:
# - env.yaml